#initial settings

path_npy_skeleton: /Users/kunkerdthaisong/ipu/ntu_rgb_proj/SampleSkeleton/ #ex:/Users/kunkerdthaisong/ipu/ntu_rgb_proj/SampleSkeleton/    
save_to: /Users/kunkerdthaisong/ipu/ntu_rgb_proj/spec/ 
drop_col: None #example drop_col=["x","y","z"]  #all feature x,y,z,frame,joint,zone,dis_from_00,dis_from_hop1,angle_from_hop1



gen_type: 1 #0:genboth, 1:gentable, 2:genspec, 3:gen_spec_from_exist_table