#initial settings

path_npy_skeleton: /Users/kunkerdthaisong/ipu/ntu_rgb_proj/SampleSkeleton/ #ex:/Users/kunkerdthaisong/ipu/ntu_rgb_proj/SampleSkeleton/    
save_img_to: /Users/kunkerdthaisong/ipu/ntu_rgb_proj/onlygodknowsperfectfeatures/data/images
save_parquet_to: /Users/kunkerdthaisong/ipu/ntu_rgb_proj/onlygodknowsperfectfeatures/data/parquet

drop_col: ["joint","frame","zone"] #example drop_col=["x","y","z"]  #all feature x,y,z,frame,joint,zone,dis_from_00,dis_from_hop1,angle_from_hop1
gen_type: 3 #0:genboth, 1:gentable, 2:genspec, 3:gen_spec_from_exist_table

feature_imp: True #defualt to fault