#initial settings

drop_col: ["joint","frame","zone"] #example drop_col=["x","y","z"]  #all feature x,y,z,frame,joint,zone,dis_from_00,dis_from_hop1,angle_from_hop1


gen_type: 3 #0:genboth, 1:gentable, 2:genspec, 3:gen_spec_from_exist_table
